/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shop_CONSTANTS_H
#define shop_CONSTANTS_H

#include "shop_types.h"



class shopConstants {
 public:
  shopConstants();

};

extern const shopConstants g_shop_constants;



#endif
